### ISSUE TITLE
OSError: ./EllipseFitError.dll: invalid ELF header

### ISSUE THREAD

**Issue by Alexsung929** [cuneytakinlar/pupil-ellipse-fit-error#4]
Hi there,
I'm working on Linux, and I have this OSError, how can I fix it?
I tried to solve this problem, and I found that someone on stackoverflow said that 'dll' file is built for Windows, it cannot possibly work on Linux.

Thanks !!

**Comment by cuneytakinlar** [comment]
Unfortunately the dll is built for windows. You cannot use it in Linux.
